import "./globals.css"
import AuthProvider from "@/components/AuthProvider"
import { ThemeProvider as NextThemesProvider } from "next-themes"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <NextThemesProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange>
          <AuthProvider>
            {children}
          </AuthProvider>
        </NextThemesProvider>
      </body>
    </html>
  )
}
