import Sidebar from "@/components/Sidebar"
import { CurrentPageProvider } from "@/contexts/CurrentPageContext"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function Layout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
      <CurrentPageProvider>
        <Sidebar>{children}</Sidebar>
        </CurrentPageProvider>
      </body>
    </html>
  )
}
