import PublicNavbar from "@/components/PublicNavbar"
import { PortfolioProvider } from "@/contexts/PortfolioProvider"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function Layout({ children, params }) {
  return (
    <div className='sm:h-screen flex flex-col max-w-5xl mx-auto md:py-10 sm:px-4'>
      <PortfolioProvider slug={params.slug}>
      <PublicNavbar slug={params.slug}/>
      {children}
      </PortfolioProvider>
    </div>
  )
}
